TEXFILES := $(shell find writeups -name '*.tex' | sort)
PDFS := $(TEXFILES:.tex=.pdf)

.PHONY: all clean

all: $(PDFS)

# A writeup may \input TikZ figures from its own figures/ subdirectory (generated by pathMgr).
# Secondary expansion is needed so $(dir $@) resolves per-target rather than at parse time;
# without it a regenerated figure would not trigger a rebuild.
.SECONDEXPANSION:

%.pdf: %.tex bib/references.bib tex/config.sty tex/macros.sty $$(wildcard $$(dir $$@)figures/*.tikz)
	cd $(dir $<) && pdflatex -interaction=nonstopmode $(notdir $<)
	cd $(dir $<) && bibtex $(basename $(notdir $<))
	cd $(dir $<) && pdflatex -interaction=nonstopmode $(notdir $<)
	cd $(dir $<) && pdflatex -interaction=nonstopmode $(notdir $<)

clean:
	find writeups -type f \( -name '*.aux' -o -name '*.bbl' -o -name '*.bcf' -o -name '*.blg' -o -name '*.fdb_latexmk' -o -name '*.fls' -o -name '*.log' -o -name '*.out' -o -name '*.run.xml' -o -name '*.synctex.gz' \) -delete
